### ISSUE TITLE
Error on build in last version of Android Studio

### ISSUE THREAD

**Issue by Mehrdad32** [aminography/FloatingWindowApp#1]
Hi, When I want to build this project, show this error to me:
Failed to resolve: androidx.core:core-ktx:1.3.0

**Comment by aminography** [comment]
Hi,
There should not be a problem with resolving `androidx.core` version 1.3.0.
Since you are in Iran, use a VPN to make sure you can reach all the dependencies. If no success, downgrade the version until the dependency gets resolved.

**Comment by Mehrdad32** [comment]
Hi, Yes I'm using VPN and can access to jcenter, google, maven, mavenCentral and Gradle... 

After downgrade to 1.0.2 problem solved! but when I installed on my phone (Android 10, Redmi Note) and it show application permission to window overly, toggle button on this page is not enabled! To fix this problem, I put this permissions in Manifest.xml to fix this:

    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.INTERNAL_SYSTEM_WINDOW " />
