### ISSUE TITLE
Ask user to grant the permission but the app doesn't appear in the list

### ISSUE THREAD

**Issue by yabee5566** [aminography/FloatingWindowApp#2]
Should add these 2 permission declaration in AndroidManifest
    
    <uses-permission android:name="android.permission.ACTION_MANAGE_OVERLAY_PERMISSION" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />

**Comment by aminography** [comment]
Hi; Thank you for raising the issue. I've mistakenly removed the permission and now it's added again.
