### ISSUE TITLE
min api lvl

### ISSUE THREAD

**Issue by bolds07** [aminography/FloatingWindowApp#4]
You build.gradle states that min api lvl is 14 but i tried to use this api on android 19 and although it does work and show the floating window correctly... once the current app minimizes the floating window minimizes too...

so it never goes to a state like you show in the demo where the floating window is on top of main screen... in andoird 29 it works fine but for 19 (and maybe lower versions) it doesnt work

am i doing something wrong?

**Comment by aminography** [comment]
Thanks for your reporting issue. I've checked it on the lower APIs before. Let me check it out.

**Comment by aminography** [comment]
Tested again, no problem on 19 (emulator). Do you try it on a real device?

**Comment by bolds07** [comment]
i tested on emulator

https://youtu.be/Es4VA8CrgA0

**Comment by aminography** [comment]
Please clone this repo and try it exactly and tell me about the result.

**Comment by bolds07** [comment]
You are right, the clone of your repo works.

The problem is your repo is kotlin and i'm working with java.... so i did a very simple port 

for testing purposes i removed all unecessary code and the got with:

```

fun show() {
        if (context.canDrawOverlays) {
         isShowing = true
            var layoutParams = WindowManager.LayoutParams().apply {
                format =     PixelFormat.TRANSLUCENT
                flags = WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE
                @Suppress("DEPRECATION")
                type = when {
                    Build.VERSION.SDK_INT >= Build.VERSION_CODES.O ->
                        WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY
                    else -> WindowManager.LayoutParams.TYPE_TOAST
                }

                gravity = Gravity.CENTER
                width = WindowManager.LayoutParams.WRAP_CONTENT
                height = WindowManager.LayoutParams.WRAP_CONTENT
            }
            (context.getSystemService(WINDOW_SERVICE) as WindowManager).addView(LayoutInflater.from(context).inflate(R.layout.layout_floating_window, null), layoutParams)
        }
    }

//then i port to java and get:

WindowManager.LayoutParams params = new WindowManager.LayoutParams();

        params.format = PixelFormat.TRANSLUCENT;
        params.flags = WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE;
        params.type = WindowManager.LayoutParams.TYPE_TOAST;


        params.gravity = Gravity.CENTER;
        params.width = WindowManager.LayoutParams.WRAP_CONTENT;
        params.height = WindowManager.LayoutParams.WRAP_CONTENT;


        ((WindowManager) getSystemService(Context.WINDOW_SERVICE)).addView(LayoutInflater.from(this).inflate(R.layout.layout_floating_window, null), params);

```

but the result is exaclty what i showed you before

https://youtu.be/4F4sPbGaw1g


if you can spot any mistake im doing please let me know... my only guess by now is that the defaults for java and kotlin are different and it causes the problem.


i would like to keep the code java

**Comment by bolds07** [comment]
do you have any idea?

**Comment by aminography** [comment]
As far as I can see, the `params.type` is not exactly the same as the repo one. Did you add manifest permissions to your project too?

**Comment by bolds07** [comment]
> As far as I can see, the `params.type` is not exactly the same as the repo one. Did you add manifest permissions to your project too?

yes it is the same... remember im testing only for api 19... it was pointless to make an conditional i even tried to force the literal value and didnt work

i have the manifest permission... my only guess is that is a real android bug

**Comment by aminography** [comment]
The only thing that seems suspicious is using the `Activity` instance. Please test again with the application-level `Context` instance:
```
Context context = getApplicationContext();
((WindowManager) context.getSystemService(Context.WINDOW_SERVICE)).addView(LayoutInflater.from(context).inflate(R.layout.layout_floating_window, null), params);
```

**Comment by aminography** [comment]
I hope I'd be able to solve the issue for you: 😁
https://stackoverflow.com/questions/63861291/create-an-overlay-window-in-android-19

<hr>

**UPDATE**

Yes, I found the problem. I've tested it and got the same result as yours :)

**Comment by bolds07** [comment]
Yes, using application context solved the problem... i dont get why so many people downvote thing on SO... people are really stupid and unhelpfull

thanks
